name: Update Time

on:
  push:
    branches: [ gh-pages ]
  #watch:
    #types: [started]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Pixiv_Spider
      run: |
        git clone https://github.com/Block-Network/AppWeb.git

    - name: Update Time
      run: |
        cd AppWeb
        ls
        ls app
        echo $(TZ=UTC-8 date +%Y-%m-%d" "%H:%M:%S) > app/updateTime.txt
       
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: UpdateTime
    
