name: Update Time

on:
  push:
    branches: [ gh-pages ]
  #watch:
    #types: [started]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Update Time
       run: |
          ls
          ls app
          echo $(TZ=UTC-8 date +%Y-%m-%d" "%H:%M:%S) > app/updateTime.txt
        
    
